plugins:
  - jekyll-paginate
  - redcarpet
  - jekyll-gist
  - pygments.rb

# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Today I Learned
tagline:          'Jeremy Cho'
description:      'A journey to document what was unknown... before this day.'
baseurl:          /

paginate:         5
